server:
  ip: 0.0.0.0
  port: 8000
  http_port: 8003
  
  vision_explain: http://你的ip或者域名:端口号/mcp/vision/explain
manager-api:

  url: http://127.0.0.1:8002/xiaozhi
  secret: 你的server.secret值
prompt_template: agent-base-prompt.txt